ERA5 timeseries
SEE-GEO/ccic_climate_record_analysis pull request #20
Opened 2024-03-23 23:31 UTC by JuliaKukulies

Here comes the cleaned-up notebook for the ERA5 time-series after your comments of #10. 

Are you happy to re-review @simonpf ?

2024-05-09 02:56 UTC, simonpf requested changes
Thanks for cleaning this up. Nonetheless, I'd like to request to minor improvements/fixes:
- Fix the unit of the cloud cover fraction.
- The text should mention that the ERA5 IWP does only include large-scale clouds.

2024-08-04 18:01 UTC, JuliaKukulies commented
> Thanks for cleaning this up. Nonetheless, I'd like to request to minor improvements/fixes:
> 
> * Fix the unit of the cloud cover fraction.
> * The text should mention that the ERA5 IWP does only include large-scale clouds.

Addressed your second comment and ignored the first since the cloud cover fraction is dimensionless :) Thanks!

2024-08-04 18:02 UTC, simonpf commented
Thanks @JuliaKukulies

2024-08-04 18:02 UTC, simonpf approved these changes

2024-08-04 18:02 UTC, merged